/**
 * Provider Registry — failover & circuit breaker integration tests
 *
 * Tests the ProviderRegistry.callLlm() chain-walk using Vitest fetch mocking.
 * No real network calls are made. DB is used for provider seeding.
 *
 * Run with: pnpm --filter @workspace/api-server test
 */

import { describe, it, expect, beforeAll, afterAll, vi, afterEach } from "vitest";
import { randomUUID } from "crypto";
import request from "supertest";
import bcrypt from "bcryptjs";
import app from "../app";
import {
  db,
  tenantsTable,
  usersTable,
  botsTable,
  providersTable,
  providerCallLogTable,
  llmConfigTable,
} from "@workspace/db";
import { eq, and, sql } from "drizzle-orm";
import { ProviderRegistry } from "../lib/provider-registry";
import { encryptKey } from "../lib/key-crypto";

// ─── Fixtures ─────────────────────────────────────────────────────────────────

const T_ID = `fo-t-${randomUUID()}`;
const ADMIN_USER_ID = `fo-admin-${randomUUID()}`;
const ADMIN_EMAIL = `fo-admin-${T_ID.slice(-8)}@test.local`;
const ADMIN_PW = "Test1234!";
const BOT_ID = `fo-bot-${randomUUID()}`;
const P1_ID = `fo-p1-${randomUUID()}`; // will return 500
const P2_ID = `fo-p2-${randomUUID()}`; // will return 200

const FAKE_KEY = "fake-test-key-12345";

/** Session cookie for an ADMIN user in T_ID — used by HTTP route authorization tests */
let adminCookie: string;

async function loginAdmin(): Promise<string> {
  const res = await request(app)
    .post("/api/v1/auth/login")
    .send({ email: ADMIN_EMAIL, password: ADMIN_PW });
  if (res.status !== 200) throw new Error(`Login failed: ${JSON.stringify(res.body)}`);
  const setCookie = res.headers["set-cookie"] as string[] | string;
  return Array.isArray(setCookie) ? setCookie[0] : setCookie;
}

beforeAll(async () => {
  const pwHash = await bcrypt.hash(ADMIN_PW, 10);

  // Seed tenant
  await db.insert(tenantsTable).values({
    id: T_ID,
    name: "Failover Test Tenant",
    slug: `fo-tenant-${T_ID.slice(-8)}`,
    status: "active",
    region: "global",
    webhookSecret: `fo-secret-${randomUUID()}`,
  }).onDuplicateKeyUpdate({ set: { id: sql`id` } });

  // Seed ADMIN user (needed for HTTP route authorization tests).
  // MySQL has no RETURNING, so the id is generated here rather than read back.
  const adminUserId = randomUUID();
  await db.insert(usersTable).values({
    id: adminUserId,
    tenantId: T_ID,
    email: ADMIN_EMAIL,
    passwordHash: pwHash,
    role: "ADMIN",
    status: "active",
  }).onDuplicateKeyUpdate({ set: { id: sql`id` } });
  // Track the generated ID for cleanup
  Object.assign(globalThis, { __fo_admin_user_id: adminUserId });

  adminCookie = await loginAdmin();

  // Seed provider 1 (openai — will be mocked to 500)
  await db.insert(providersTable).values({
    id: P1_ID,
    tenantId: T_ID,
    kind: "LLM",
    vendor: "openai",
    displayName: "OpenAI (Failover Test)",
    authMode: "bearer",
    apiKeyEncrypted: encryptKey(FAKE_KEY),
    enabled: true,
  }).onDuplicateKeyUpdate({ set: { id: sql`id` } });

  // Seed provider 2 (anthropic — will be mocked to succeed)
  await db.insert(providersTable).values({
    id: P2_ID,
    tenantId: T_ID,
    kind: "LLM",
    vendor: "anthropic",
    displayName: "Anthropic (Failover Test)",
    authMode: "api-key",
    apiKeyEncrypted: encryptKey(FAKE_KEY),
    enabled: true,
  }).onDuplicateKeyUpdate({ set: { id: sql`id` } });

  // Seed bot with explicit two-provider chain
  await db.insert(botsTable).values({
    id: BOT_ID,
    displayName: "Failover Test Bot",
    sipExtension: "FO-9999",
    status: "OFFLINE",
    activeCalls: 0,
    tenantId: T_ID,
    supportedLanguages: ["en"],
    defaultGreetingLanguage: "en",
    timezone: "UTC",
    endpointSilenceMs: 1200,
    backchannelThresholdMs: 700,
    silenceRecoverySecs: 6,
    direction: "inbound",
    llmChainJson: [
      { provider_id: P1_ID, model_id: "gpt-4o-mini" },
      { provider_id: P2_ID, model_id: "claude-3-haiku-20240307" },
    ],
  }).onDuplicateKeyUpdate({ set: { id: sql`id` } });
});

afterAll(async () => {
  await db.delete(botsTable).where(eq(botsTable.id, BOT_ID)).catch(() => {});
  await db.delete(providersTable).where(eq(providersTable.tenantId, T_ID)).catch(() => {});
  await db.delete(providerCallLogTable).where(eq(providerCallLogTable.tenantId, T_ID)).catch(() => {});
  // Clean up the seeded ADMIN user (ID was generated by the DB)
  const foAdminId = (globalThis as Record<string, unknown>)["__fo_admin_user_id"] as string | undefined;
  if (foAdminId) await db.delete(usersTable).where(eq(usersTable.id, foAdminId)).catch(() => {});
  await db.delete(tenantsTable).where(eq(tenantsTable.id, T_ID)).catch(() => {});
});

afterEach(() => {
  vi.restoreAllMocks();
});

// ─── Helpers ─────────────────────────────────────────────────────────────────

function makeOpenAISuccessResponse(): Response {
  return new Response(
    JSON.stringify({
      choices: [{ message: { content: "Hello from OpenAI" } }],
      usage: { prompt_tokens: 10, completion_tokens: 5 },
    }),
    { status: 200, headers: { "Content-Type": "application/json" } }
  );
}

function makeAnthropicSuccessResponse(): Response {
  return new Response(
    JSON.stringify({
      content: [{ text: "Hello from Anthropic" }],
      usage: { input_tokens: 10, output_tokens: 5 },
    }),
    { status: 200, headers: { "Content-Type": "application/json" } }
  );
}

function make500Response(): Response {
  return new Response(JSON.stringify({ error: { message: "Internal Server Error" } }), {
    status: 500,
    headers: { "Content-Type": "application/json" },
  });
}

// ─── Tests ────────────────────────────────────────────────────────────────────

describe("ProviderRegistry.callLlm — failover chain", () => {
  it("returns the first provider's response when it succeeds", async () => {
    const registry = new ProviderRegistry();
    vi.spyOn(global, "fetch").mockResolvedValueOnce(makeOpenAISuccessResponse());

    const result = await registry.callLlm({
      systemPrompt: "You are a test bot.",
      userPrompt: "Say hello.",
      tenantId: T_ID,
      botId: BOT_ID,
    });

    expect(result.text).toBe("Hello from OpenAI");
    expect(result.vendor).toBe("openai");
    expect(result.providerId).toBe(P1_ID);
  });

  it("falls over to provider 2 when provider 1 returns HTTP 500", async () => {
    const registry = new ProviderRegistry();

    // First call → OpenAI 500; second call → Anthropic 200
    vi.spyOn(global, "fetch")
      .mockResolvedValueOnce(make500Response())
      .mockResolvedValueOnce(makeAnthropicSuccessResponse());

    const result = await registry.callLlm({
      systemPrompt: "You are a test bot.",
      userPrompt: "Say hello.",
      tenantId: T_ID,
      botId: BOT_ID,
    });

    expect(result.text).toBe("Hello from Anthropic");
    expect(result.vendor).toBe("anthropic");
    expect(result.providerId).toBe(P2_ID);
  });

  it("writes provider_call_log rows for each attempt", async () => {
    const registry = new ProviderRegistry();

    // Provider 1 fails, provider 2 succeeds
    vi.spyOn(global, "fetch")
      .mockResolvedValueOnce(make500Response())
      .mockResolvedValueOnce(makeAnthropicSuccessResponse());

    await registry.callLlm({
      systemPrompt: "Log test.",
      userPrompt: "Test.",
      tenantId: T_ID,
      botId: BOT_ID,
    });

    // Allow async log insert to settle
    await new Promise((r) => setTimeout(r, 200));

    const logs = await db
      .select()
      .from(providerCallLogTable)
      .where(and(eq(providerCallLogTable.tenantId, T_ID), eq(providerCallLogTable.providerKind, "LLM")));

    // Should have at least 2 log rows: one error (openai) + one success (anthropic)
    const errorLog = logs.find((l) => l.outcomeStatus === "error" && l.providerVendor === "openai");
    const successLog = logs.find((l) => l.outcomeStatus === "success" && l.providerVendor === "anthropic");

    expect(errorLog).toBeDefined();
    expect(errorLog?.providerId).toBe(P1_ID);
    expect(successLog).toBeDefined();
    expect(successLog?.providerId).toBe(P2_ID);
  });

  it("throws when all providers in the chain fail", async () => {
    const registry = new ProviderRegistry();

    vi.spyOn(global, "fetch")
      .mockResolvedValueOnce(make500Response())  // openai fails
      .mockResolvedValueOnce(make500Response());  // anthropic also fails

    await expect(
      registry.callLlm({
        systemPrompt: "All fail test.",
        userPrompt: "Test.",
        tenantId: T_ID,
        botId: BOT_ID,
      })
    ).rejects.toThrow("All LLM providers exhausted");
  });

  it("opens the circuit breaker after repeated failures and skips the provider", async () => {
    const registry = new ProviderRegistry();

    // Trip provider 1's breaker past the threshold (5 failures)
    for (let i = 0; i < 5; i++) {
      vi.spyOn(global, "fetch")
        .mockResolvedValueOnce(make500Response())  // p1 fails
        .mockResolvedValueOnce(makeAnthropicSuccessResponse()); // p2 succeeds
      await registry.callLlm({
        systemPrompt: "Breaker test.",
        userPrompt: `Trip ${i}.`,
        tenantId: T_ID,
        botId: BOT_ID,
      });
      vi.restoreAllMocks();
    }

    // Now provider 1's breaker should be open — only ONE fetch (provider 2)
    const fetchSpy = vi.spyOn(global, "fetch")
      .mockResolvedValueOnce(makeAnthropicSuccessResponse());

    const result = await registry.callLlm({
      systemPrompt: "Breaker open test.",
      userPrompt: "Should skip p1.",
      tenantId: T_ID,
      botId: BOT_ID,
    });

    expect(result.vendor).toBe("anthropic");
    // fetch should only have been called once (provider 2 only)
    expect(fetchSpy).toHaveBeenCalledTimes(1);
  });
});

describe("ProviderRegistry — STT/TTS resolution", () => {
  it("resolveStt returns null when no STT providers are configured", async () => {
    const registry = new ProviderRegistry();
    const result = await registry.resolveStt(T_ID, "en", BOT_ID);
    // No STT providers seeded for this tenant → null
    expect(result).toBeNull();
  });

  it("resolveTts returns null when no TTS providers are configured", async () => {
    const registry = new ProviderRegistry();
    const result = await registry.resolveTts(T_ID, "en", BOT_ID);
    expect(result).toBeNull();
  });
});

// ─── SSRF protection — runtime callLlm() ─────────────────────────────────────

describe("ProviderRegistry — SSRF protection at runtime", () => {
  const LOOPBACK_PROVIDER_ID = `fo-ssrf-${randomUUID()}`;
  const BOT_SSRF = `fo-ssrf-bot-${randomUUID()}`;

  beforeAll(async () => {
    // Store a provider whose baseUrl points at the loopback address.
    // In a real attack this would be inserted directly into the DB after
    // bypassing the create route (e.g., in a race between DNS validation and
    // use). The registry must reject it at call time regardless.
    await db.insert(providersTable).values({
      id: LOOPBACK_PROVIDER_ID,
      tenantId: T_ID,
      kind: "LLM",
      vendor: "openai-compatible",
      displayName: "SSRF Loopback Provider",
      baseUrl: "http://127.0.0.1:8080", // loopback — must be blocked
      authMode: "bearer",
      apiKeyEncrypted: encryptKey("ssrf-test-key"),
      enabled: true,
    }).onDuplicateKeyUpdate({ set: { id: sql`id` } });

    await db.insert(botsTable).values({
      id: BOT_SSRF,
      displayName: "SSRF Test Bot",
      sipExtension: "FO-SSRF",
      status: "OFFLINE",
      activeCalls: 0,
      tenantId: T_ID,
      supportedLanguages: ["en"],
      defaultGreetingLanguage: "en",
      timezone: "UTC",
      endpointSilenceMs: 1200,
      backchannelThresholdMs: 700,
      silenceRecoverySecs: 6,
      direction: "inbound",
      llmChainJson: [{ provider_id: LOOPBACK_PROVIDER_ID, model_id: "custom-model" }],
    }).onDuplicateKeyUpdate({ set: { id: sql`id` } });
  });

  afterAll(async () => {
    await db.delete(botsTable).where(eq(botsTable.id, BOT_SSRF)).catch(() => {});
    await db.delete(providersTable).where(eq(providersTable.id, LOOPBACK_PROVIDER_ID)).catch(() => {});
  });

  it("rejects a private/loopback baseUrl at runtime before making an outbound call", async () => {
    const registry = new ProviderRegistry();
    const fetchSpy = vi.spyOn(global, "fetch"); // must NOT be called

    await expect(
      registry.callLlm({
        systemPrompt: "Test.",
        userPrompt: "Test.",
        tenantId: T_ID,
        botId: BOT_SSRF,
      })
    ).rejects.toThrow();

    // fetch must not have been called with the loopback URL
    const loopbackCalls = fetchSpy.mock.calls.filter((args) =>
      String(args[0]).includes("127.0.0.1")
    );
    expect(loopbackCalls).toHaveLength(0);
  });
});

// ─── SSRF protection — validateBaseUrl() unit tests ──────────────────────────

describe("validateBaseUrl — SSRF guard unit tests", () => {
  it("rejects http://127.0.0.1 (loopback IPv4)", async () => {
    const { validateBaseUrl } = await import("../lib/ssrf-guard.js");
    await expect(validateBaseUrl("http://127.0.0.1/api")).rejects.toThrow();
  });

  it("rejects http://10.0.0.1 (RFC-1918 private)", async () => {
    const { validateBaseUrl } = await import("../lib/ssrf-guard.js");
    await expect(validateBaseUrl("http://10.0.0.1/api")).rejects.toThrow();
  });

  it("rejects http://192.168.1.1 (RFC-1918 private)", async () => {
    const { validateBaseUrl } = await import("../lib/ssrf-guard.js");
    await expect(validateBaseUrl("http://192.168.1.1/v1")).rejects.toThrow();
  });

  it("rejects http://172.20.0.1 (RFC-1918 private 172.16-31 range)", async () => {
    const { validateBaseUrl } = await import("../lib/ssrf-guard.js");
    await expect(validateBaseUrl("http://172.20.0.1/v1")).rejects.toThrow();
  });

  it("rejects http://169.254.169.254 (cloud metadata link-local)", async () => {
    const { validateBaseUrl } = await import("../lib/ssrf-guard.js");
    await expect(validateBaseUrl("http://169.254.169.254/latest/meta-data/")).rejects.toThrow();
  });

  it("rejects ftp:// scheme", async () => {
    const { validateBaseUrl } = await import("../lib/ssrf-guard.js");
    await expect(validateBaseUrl("ftp://example.com/v1")).rejects.toThrow();
  });

  it("rejects file:// scheme", async () => {
    const { validateBaseUrl } = await import("../lib/ssrf-guard.js");
    await expect(validateBaseUrl("file:///etc/passwd")).rejects.toThrow();
  });
});

// ─── isPrivateIp unit tests ───────────────────────────────────────────────────

describe("isPrivateIp — IPv4 range checks", () => {
  it("identifies 10.x.x.x as private", async () => {
    const { isPrivateIp } = await import("../lib/ssrf-guard.js");
    expect(isPrivateIp("10.0.0.1")).toBe(true);
    expect(isPrivateIp("10.255.255.255")).toBe(true);
  });

  it("identifies 172.16-31.x.x as private", async () => {
    const { isPrivateIp } = await import("../lib/ssrf-guard.js");
    expect(isPrivateIp("172.16.0.1")).toBe(true);
    expect(isPrivateIp("172.31.255.255")).toBe(true);
    expect(isPrivateIp("172.15.0.1")).toBe(false); // just outside the range
    expect(isPrivateIp("172.32.0.1")).toBe(false);
  });

  it("identifies 192.168.x.x as private", async () => {
    const { isPrivateIp } = await import("../lib/ssrf-guard.js");
    expect(isPrivateIp("192.168.0.1")).toBe(true);
    expect(isPrivateIp("192.167.0.1")).toBe(false);
  });

  it("identifies 127.x.x.x as loopback", async () => {
    const { isPrivateIp } = await import("../lib/ssrf-guard.js");
    expect(isPrivateIp("127.0.0.1")).toBe(true);
    expect(isPrivateIp("127.255.255.255")).toBe(true);
  });

  it("identifies 169.254.x.x as link-local", async () => {
    const { isPrivateIp } = await import("../lib/ssrf-guard.js");
    expect(isPrivateIp("169.254.169.254")).toBe(true);
  });

  it("does not flag public IPs as private", async () => {
    const { isPrivateIp } = await import("../lib/ssrf-guard.js");
    expect(isPrivateIp("8.8.8.8")).toBe(false);
    expect(isPrivateIp("1.1.1.1")).toBe(false);
    expect(isPrivateIp("52.0.0.1")).toBe(false);
  });
});

describe("isPrivateIp — IPv6 range checks (including bracketed literals)", () => {
  it("identifies ::1 (loopback) as private", async () => {
    const { isPrivateIp } = await import("../lib/ssrf-guard.js");
    expect(isPrivateIp("::1")).toBe(true);
  });

  it("identifies [::1] (bracketed loopback as returned by url.hostname) as private", async () => {
    const { isPrivateIp } = await import("../lib/ssrf-guard.js");
    expect(isPrivateIp("[::1]")).toBe(true);
  });

  it("identifies ULA fc00::/7 addresses (fc:: and fd::) as private", async () => {
    const { isPrivateIp } = await import("../lib/ssrf-guard.js");
    expect(isPrivateIp("fc00::1")).toBe(true);
    expect(isPrivateIp("fd12:3456:789a::1")).toBe(true);
    expect(isPrivateIp("[fd00::1]")).toBe(true); // bracketed ULA
  });

  it("identifies fe80::/10 link-local addresses as private (full range fe80::–febf::)", async () => {
    const { isPrivateIp } = await import("../lib/ssrf-guard.js");
    expect(isPrivateIp("fe80::1")).toBe(true);   // classic link-local
    expect(isPrivateIp("fe90::1")).toBe(true);   // fe9x in range
    expect(isPrivateIp("fea0::1")).toBe(true);   // feax in range
    expect(isPrivateIp("feb0::1")).toBe(true);   // febx in range
    expect(isPrivateIp("febf::1")).toBe(true);   // top of range
    expect(isPrivateIp("[fe80::1]")).toBe(true); // bracketed link-local
    expect(isPrivateIp("fec0::1")).toBe(false);  // fec0 is outside fe80::/10
  });

  it("identifies IPv4-mapped private addresses (::ffff:192.168.x.x) as private", async () => {
    const { isPrivateIp } = await import("../lib/ssrf-guard.js");
    expect(isPrivateIp("::ffff:192.168.1.1")).toBe(true);
    expect(isPrivateIp("::ffff:10.0.0.1")).toBe(true);
    expect(isPrivateIp("::ffff:127.0.0.1")).toBe(true);
    expect(isPrivateIp("[::ffff:192.168.1.1]")).toBe(true); // bracketed
  });

  it("does not flag public IPv6 addresses as private", async () => {
    const { isPrivateIp } = await import("../lib/ssrf-guard.js");
    expect(isPrivateIp("2001:4860:4860::8888")).toBe(false); // Google DNS
    expect(isPrivateIp("2606:4700:4700::1111")).toBe(false); // Cloudflare DNS
  });
});

describe("validateBaseUrl — IPv6 SSRF tests", () => {
  it("rejects http://[::1] (bracketed IPv6 loopback)", async () => {
    const { validateBaseUrl } = await import("../lib/ssrf-guard.js");
    await expect(validateBaseUrl("http://[::1]/api")).rejects.toThrow();
  });

  it("rejects http://[::ffff:192.168.1.1] (IPv4-mapped private via IPv6)", async () => {
    const { validateBaseUrl } = await import("../lib/ssrf-guard.js");
    await expect(validateBaseUrl("http://[::ffff:192.168.1.1]/v1")).rejects.toThrow();
  });

  it("rejects http://[fe80::1] (link-local IPv6)", async () => {
    const { validateBaseUrl } = await import("../lib/ssrf-guard.js");
    await expect(validateBaseUrl("http://[fe80::1]/v1")).rejects.toThrow();
  });

  it("rejects http://[fd00::1] (ULA IPv6)", async () => {
    const { validateBaseUrl } = await import("../lib/ssrf-guard.js");
    await expect(validateBaseUrl("http://[fd00::1]/v1")).rejects.toThrow();
  });
});

describe("isPrivateIp — NAT64 (64:ff9b::/96) checks", () => {
  it("blocks NAT64 dotted-decimal private embedded IPv4 (64:ff9b::192.168.1.1)", async () => {
    const { isPrivateIp } = await import("../lib/ssrf-guard.js");
    expect(isPrivateIp("64:ff9b::192.168.1.1")).toBe(true);
    expect(isPrivateIp("64:ff9b::10.0.0.1")).toBe(true);
    expect(isPrivateIp("64:ff9b::127.0.0.1")).toBe(true);
  });

  it("blocks NAT64 hex-group private embedded IPv4 (64:ff9b::c0a8:0101 = 192.168.1.1)", async () => {
    const { isPrivateIp } = await import("../lib/ssrf-guard.js");
    // 192.168.1.1 → c0a8:0101
    expect(isPrivateIp("64:ff9b::c0a8:0101")).toBe(true);
    // 10.0.0.1 → 0a00:0001
    expect(isPrivateIp("64:ff9b::0a00:0001")).toBe(true);
    // 127.0.0.1 → 7f00:0001
    expect(isPrivateIp("64:ff9b::7f00:0001")).toBe(true);
    // 169.254.169.254 (cloud metadata) → a9fe:a9fe
    expect(isPrivateIp("64:ff9b::a9fe:a9fe")).toBe(true);
  });

  it("does not block NAT64 with public embedded IPv4 (64:ff9b::8.8.8.8 = Google DNS)", async () => {
    const { isPrivateIp } = await import("../lib/ssrf-guard.js");
    expect(isPrivateIp("64:ff9b::8.8.8.8")).toBe(false);
    // 8.8.8.8 → 0808:0808
    expect(isPrivateIp("64:ff9b::0808:0808")).toBe(false);
  });
});

// ─── Ollama legacy fallback ───────────────────────────────────────────────────

describe("ProviderRegistry — Ollama via llm_config.primary", () => {
  it("dispatches to Ollama when OLLAMA_API_URL is set and llm_config.primary is 'ollama'", async () => {
    const OLLAMA_URL = "http://fake-ollama.internal/v1";
    const OLLAMA_TENANT = `fo-ollama-${randomUUID()}`;

    // Seed a tenant with llm_config.primary = "ollama"
    await db.insert(tenantsTable).values({
      id: OLLAMA_TENANT,
      name: "Ollama Test Tenant",
      slug: `fo-ollama-${OLLAMA_TENANT.slice(-8)}`,
      status: "active",
      region: "global",
      webhookSecret: `fo-ollama-secret-${randomUUID()}`,
    }).onDuplicateKeyUpdate({ set: { id: sql`id` } });

    // Insert llm_config selecting ollama as primary.
    // Uses the ORM rather than raw SQL so it stays dialect-agnostic.
    await db.insert(llmConfigTable).values({
      id: `lc-ollama-${randomUUID()}`,
      tenantId: OLLAMA_TENANT,
      primary: "ollama",
      fallbackChain: ["openai"],
      timeoutMs: 5000,
      maxRetries: 1,
      circuitBreakerFailureThreshold: 5,
      circuitBreakerRecoveryTimeoutSec: 30,
      updatedAt: new Date(),
    }).onDuplicateKeyUpdate({ set: { id: sql`id` } });

    // Mock OLLAMA_API_URL env var and fetch
    const origEnv = process.env.OLLAMA_API_URL;
    process.env.OLLAMA_API_URL = OLLAMA_URL;

    const fetchSpy = vi.spyOn(global, "fetch").mockImplementation(async (url: RequestInfo | URL) => {
      if (String(url).includes(OLLAMA_URL)) {
        return new Response(
          JSON.stringify({
            choices: [{ message: { content: "Hello from Ollama" } }],
            usage: { prompt_tokens: 5, completion_tokens: 3 },
          }),
          { status: 200, headers: { "Content-Type": "application/json" } }
        );
      }
      throw new Error("Unexpected fetch to: " + String(url));
    });

    try {
      const registry = new ProviderRegistry();
      const result = await registry.callLlm({
        systemPrompt: "You are a test assistant.",
        userPrompt: "Say hi.",
        tenantId: OLLAMA_TENANT,
      });

      expect(result.text).toBe("Hello from Ollama");
      expect(result.vendor).toBe("ollama");

      // Verify fetch was called with the Ollama URL
      const ollamaCalls = fetchSpy.mock.calls.filter((args) =>
        String(args[0]).startsWith(OLLAMA_URL)
      );
      expect(ollamaCalls.length).toBeGreaterThan(0);
    } finally {
      process.env.OLLAMA_API_URL = origEnv;
      await db
        .delete(llmConfigTable)
        .where(eq(llmConfigTable.tenantId, OLLAMA_TENANT))
        .catch(() => {});
      await db.delete(tenantsTable).where(eq(tenantsTable.id, OLLAMA_TENANT)).catch(() => {});
    }
  });
});

// ─── Authorization: model-catalog mutations are platform-admin-only ────────────

describe("Model Catalog — tenant users cannot mutate the global catalogue", () => {
  it("POST /v1/model-catalog returns 403 for an authenticated ADMIN tenant user", async () => {
    const res = await request(app)
      .post("/api/v1/model-catalog")
      .set("Cookie", adminCookie)
      .send({ vendor: "openai", kind: "LLM", modelId: "gpt-99", displayName: "GPT 99" });
    expect(res.status).toBe(403);
  });

  it("PATCH /v1/model-catalog/:id returns 403 for an authenticated ADMIN tenant user", async () => {
    // Fetch any existing catalogue row to get a real ID (no auth required for GET)
    const listRes = await request(app)
      .get("/api/v1/model-catalog?deprecated=false")
      .set("Cookie", adminCookie);
    expect(listRes.status).toBe(200);
    const rows = listRes.body as Array<{ id: string }>;
    expect(rows.length).toBeGreaterThan(0);

    const patchRes = await request(app)
      .patch(`/api/v1/model-catalog/${rows[0].id}`)
      .set("Cookie", adminCookie)
      .send({ deprecated: true });
    expect(patchRes.status).toBe(403);
  });
});

// ─── Authorization: platform-pooled provider credential protection ────────────

describe("Providers — platform-pooled provider credential protection", () => {
  const POOLED_ID = `fo-pooled-${randomUUID()}`;

  beforeAll(async () => {
    await db.insert(providersTable).values({
      id: POOLED_ID,
      tenantId: null, // platform-pooled
      kind: "LLM",
      vendor: "openai",
      displayName: "Platform OpenAI Pool",
      authMode: "bearer",
      apiKeyEncrypted: encryptKey("platform-secret-api-key-12345678"),
      enabled: true,
    }).onDuplicateKeyUpdate({ set: { id: sql`id` } });
  });

  afterAll(async () => {
    await db.delete(providersTable).where(eq(providersTable.id, POOLED_ID)).catch(() => {});
  });

  it("GET /v1/providers returns pooled provider but with null keyPreview", async () => {
    const res = await request(app)
      .get("/api/v1/providers")
      .set("Cookie", adminCookie);
    expect(res.status).toBe(200);
    const pooled = (res.body as Array<{ id: string; keyPreview: string | null; isPlatformPooled: boolean }>)
      .find((r) => r.id === POOLED_ID);
    expect(pooled).toBeDefined();
    expect(pooled!.isPlatformPooled).toBe(true);
    // keyPreview must be null — credential material must not be exposed to tenant users
    expect(pooled!.keyPreview).toBeNull();
  });

  it("POST /v1/providers/:id/test-key for pooled provider returns 403", async () => {
    const res = await request(app)
      .post(`/api/v1/providers/${POOLED_ID}/test-key`)
      .set("Cookie", adminCookie);
    expect(res.status).toBe(403);
  });
});

// ─── Cross-tenant provider isolation ─────────────────────────────────────────

describe("ProviderRegistry — cross-tenant isolation", () => {
  const T_OTHER = `fo-other-${randomUUID()}`;
  const P_OTHER = `fo-other-p-${randomUUID()}`;
  const BOT_CROSS = `fo-cross-bot-${randomUUID()}`;

  beforeAll(async () => {
    // Seed a second tenant with its own LLM provider
    await db.insert(tenantsTable).values({
      id: T_OTHER,
      name: "Other Tenant",
      slug: `other-${T_OTHER.slice(-6)}`,
      status: "active",
      region: "global",
      webhookSecret: `other-secret-${randomUUID()}`,
    }).onDuplicateKeyUpdate({ set: { id: sql`id` } });

    await db.insert(providersTable).values({
      id: P_OTHER,
      tenantId: T_OTHER,
      kind: "LLM",
      vendor: "openai",
      displayName: "Other Tenant's Provider",
      authMode: "bearer",
      apiKeyEncrypted: encryptKey("other-tenant-secret-key"),
      enabled: true,
    }).onDuplicateKeyUpdate({ set: { id: sql`id` } });

    // Bot belonging to T_ID whose llmChainJson references T_OTHER's provider
    await db.insert(botsTable).values({
      id: BOT_CROSS,
      displayName: "Cross-Tenant Attack Bot",
      sipExtension: "FO-CROSS",
      status: "OFFLINE",
      activeCalls: 0,
      tenantId: T_ID,
      supportedLanguages: ["en"],
      defaultGreetingLanguage: "en",
      timezone: "UTC",
      endpointSilenceMs: 1200,
      backchannelThresholdMs: 700,
      silenceRecoverySecs: 6,
      direction: "inbound",
      // Attempt to reference a provider from T_OTHER (cross-tenant attack)
      llmChainJson: [
        { provider_id: P_OTHER, model_id: "gpt-4o" },
      ],
    }).onDuplicateKeyUpdate({ set: { id: sql`id` } });
  });

  afterAll(async () => {
    await db.delete(botsTable).where(eq(botsTable.id, BOT_CROSS)).catch(() => {});
    await db.delete(providersTable).where(eq(providersTable.id, P_OTHER)).catch(() => {});
    await db.delete(tenantsTable).where(eq(tenantsTable.id, T_OTHER)).catch(() => {});
  });

  it("cannot use another tenant's provider via explicit bot chain", async () => {
    const registry = new ProviderRegistry();

    // The chain references P_OTHER which belongs to T_OTHER, not T_ID.
    // buildLlmChain must silently drop it (cross-tenant scope rejection).
    // With no valid entries, it falls back to the env-var legacy chain.
    // Since no OPENAI_API_KEY etc. are set in the test environment, the
    // returned chain should be empty OR skip directly to env-var fallback.
    const chain = await registry.buildLlmChain(T_ID, BOT_CROSS);

    // P_OTHER must NOT appear in the resolved chain under any circumstances
    const providerIds = chain.map((e) => e.provider.id);
    expect(providerIds).not.toContain(P_OTHER);
  });

  it("resolveStt rejects a foreign tenant's STT provider", async () => {
    // Seed a foreign STT provider
    const P_FOREIGN_STT = `fo-fstt-${randomUUID()}`;
    await db.insert(providersTable).values({
      id: P_FOREIGN_STT,
      tenantId: T_OTHER,
      kind: "STT",
      vendor: "deepgram",
      displayName: "Foreign STT",
      authMode: "bearer",
      apiKeyEncrypted: encryptKey("foreign-stt-key"),
      enabled: true,
    }).onDuplicateKeyUpdate({ set: { id: sql`id` } });

    // Bot in T_ID referencing foreign STT
    const BOT_STT = `fo-bstt-${randomUUID()}`;
    await db.insert(botsTable).values({
      id: BOT_STT,
      displayName: "STT Cross-Tenant Bot",
      sipExtension: "FO-STT",
      status: "OFFLINE",
      activeCalls: 0,
      tenantId: T_ID,
      supportedLanguages: ["en"],
      defaultGreetingLanguage: "en",
      timezone: "UTC",
      endpointSilenceMs: 1200,
      backchannelThresholdMs: 700,
      silenceRecoverySecs: 6,
      direction: "inbound",
      sttMapJson: { en: { provider_id: P_FOREIGN_STT, model_id: "nova-2" } },
    }).onDuplicateKeyUpdate({ set: { id: sql`id` } });

    const registry = new ProviderRegistry();
    const result = await registry.resolveStt(T_ID, "en", BOT_STT);

    // The foreign provider must be rejected → result falls through to tenant-level
    // STT providers (none configured for T_ID) → null
    expect(result).toBeNull();

    await db.delete(botsTable).where(eq(botsTable.id, BOT_STT)).catch(() => {});
    await db.delete(providersTable).where(eq(providersTable.id, P_FOREIGN_STT)).catch(() => {});
  });
});
