import { ChangeEvent, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Activity, CalendarClock, Copy, Download, FileUp, Loader2, Megaphone, Pause, Play, Plus, Square, Upload, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";

const BASE = import.meta.env.BASE_URL.replace(/\/$/, "");
async function request<T>(path: string, options?: RequestInit) {
  const response = await fetch(`${BASE}/api${path}`, { credentials: "include", ...options });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.error ?? "Request failed");
  return body as T;
}
type Campaign = { id: string; name: string; botId: string; objectivePrompt: string; status: string; concurrencyCap: number; scheduleJson?: { startAt?: string; endAt?: string; callingWindowStart?: string; callingWindowEnd?: string }; metrics: { total: number; queued: number; dialing: number; blocked: number; done: number; goalMet: number } };
type Bot = { id: string; displayName: string };
type ImportReport = { headers: string[]; total: number; allowed: number; blocked: number; rows: Array<{ row: number; phone?: string; state: string; reason?: string }> };

export default function CampaignsPage() {
  const queryClient = useQueryClient(); const { toast } = useToast();
  const [open, setOpen] = useState(false); const [selected, setSelected] = useState<Campaign | null>(null);
  const [name, setName] = useState(""); const [botId, setBotId] = useState(""); const [objectivePrompt, setObjective] = useState("");
  const [concurrencyCap, setConcurrency] = useState("2"); const [csv, setCsv] = useState(""); const [phoneColumn, setPhoneColumn] = useState("phone"); const [variableColumns, setVariableColumns] = useState<string[]>([]);
  const [importReport, setImportReport] = useState<ImportReport | null>(null); const [startAt, setStartAt] = useState(""); const [endAt, setEndAt] = useState(""); const [windowStart, setWindowStart] = useState("09:00"); const [windowEnd, setWindowEnd] = useState("17:00");
  const campaigns = useQuery({ queryKey: ["campaigns"], queryFn: () => request<Campaign[]>("/v1/campaigns"), refetchInterval: 5_000 });
  const bots = useQuery({ queryKey: ["campaign-bots"], queryFn: () => request<Bot[]>("/v1/bots") });
  const refresh = () => { queryClient.invalidateQueries({ queryKey: ["campaigns"] }); if (selected) queryClient.invalidateQueries({ queryKey: ["campaign-contacts", selected.id] }); };
  const create = useMutation({ mutationFn: () => request<Campaign>("/v1/campaigns", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, botId, objectivePrompt, concurrencyCap: Number(concurrencyCap), scheduleJson: { startAt: startAt || undefined, endAt: endAt || undefined, callingWindowStart: windowStart, callingWindowEnd: windowEnd }, retryPolicyJson: { max_attempts: 3, spacing_minutes: 30, per_outcome: { NO_ANSWER: "retry", BUSY: "retry" } } }) }), onSuccess: (campaign) => { refresh(); setSelected(campaign); setOpen(false); setName(""); setObjective(""); toast({ title: "Campaign created", description: "Import contacts, review them, then launch when ready." }); }, onError: (error: Error) => toast({ title: error.message, variant: "destructive" }) });
  const lifecycle = useMutation({ mutationFn: ({ id, status }: { id: string; status: string }) => request<Campaign>(`/v1/campaigns/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }), onSuccess: (campaign) => { setSelected(campaign); refresh(); toast({ title: `Campaign ${campaign.status.toLowerCase()}` }); }, onError: (error: Error) => toast({ title: error.message, variant: "destructive" }) });
  const previewCsv = useMutation({ mutationFn: () => request<ImportReport>(`/v1/campaigns/${selected?.id}/contacts/import`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ csv, phoneColumn, variableColumns, previewOnly: true }) }), onSuccess: setImportReport, onError: (error: Error) => toast({ title: error.message, variant: "destructive" }) });
  const importCsv = useMutation({ mutationFn: () => request<ImportReport>(`/v1/campaigns/${selected?.id}/contacts/import`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ csv, phoneColumn, variableColumns, previewOnly: false }) }), onSuccess: (report) => { setCsv(""); setImportReport(null); refresh(); toast({ title: "Contacts imported", description: `${report.allowed} queued · ${report.blocked} blocked by compliance` }); }, onError: (error: Error) => toast({ title: error.message, variant: "destructive" }) });
  const contacts = useQuery({ queryKey: ["campaign-contacts", selected?.id], enabled: !!selected, queryFn: () => request<Array<{ id: string; phoneE164: string; state: string; attempts: number; lastDisposition: string | null; blockReason: string | null }>>(`/v1/campaigns/${selected?.id}/contacts`), refetchInterval: 5_000 });
  const dispositions = useQuery({ queryKey: ["campaign-dispositions", selected?.id], enabled: !!selected, queryFn: () => request<Array<{ id: string; code: string; summaryText: string | null; createdAt: string }>>(`/v1/campaigns/${selected?.id}/dispositions`), refetchInterval: 5_000 });
  const callbacks = useQuery({ queryKey: ["campaign-callbacks", selected?.id], enabled: !!selected, queryFn: () => request<Array<{ id: string; scheduledFor: string; note: string | null; fulfilled: boolean }>>(`/v1/campaigns/${selected?.id}/callbacks`), refetchInterval: 5_000 });
  const clone = useMutation({ mutationFn: (id: string) => request<Campaign>(`/v1/campaigns/${id}/clone`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ copyContacts: false }) }), onSuccess: (campaign) => { refresh(); setSelected(campaign); toast({ title: "A/B variant created", description: "The clone is a draft with an independent queue." }); }, onError: (error: Error) => toast({ title: error.message, variant: "destructive" }) });
  const stop = useMutation({ mutationFn: (id: string) => request<Campaign>(`/v1/campaigns/${id}/stop`, { method: "POST" }), onSuccess: (campaign) => { setSelected(campaign); refresh(); toast({ title: "Campaign stopped", description: "It cannot be restarted; clone it to run a new variant." }); }, onError: (error: Error) => toast({ title: error.message, variant: "destructive" }) });
  const onFile = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { const text = String(reader.result ?? ""); setCsv(text); setImportReport(null); const header = text.split(/\r?\n/, 1)[0].replace(/^\uFEFF/, "").split(",").map((item) => item.trim().replace(/^"|"$/g, "")); if (header.length) { setPhoneColumn(header.find((item) => /phone|mobile|number/i.test(item)) ?? header[0]); setVariableColumns(header.filter((item) => !/phone|mobile|number/i.test(item))); } }; reader.readAsText(file); };

  return <div className="p-6 space-y-6">
    <div className="flex flex-wrap items-start justify-between gap-3"><div className="flex gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-md bg-primary/10 text-primary"><Megaphone className="h-5 w-5" /></div><div><h1 className="text-lg font-bold">Campaigns</h1><p className="text-sm text-muted-foreground">Compliance-gated outbound sequences with live queue visibility.</p></div></div><Button onClick={() => setOpen(true)}><Plus className="mr-2 h-4 w-4" /> New campaign</Button></div>
    <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(360px,0.8fr)]">
      <div className="space-y-3">{campaigns.isLoading ? <div className="rounded border p-8 text-center text-muted-foreground">Loading campaigns…</div> : campaigns.data?.length === 0 ? <div className="rounded border border-dashed p-10 text-center"><Megaphone className="mx-auto h-7 w-7 text-muted-foreground" /><p className="mt-3 font-medium">No campaigns yet</p><p className="mt-1 text-sm text-muted-foreground">Create a campaign to import a calling list and manage its queue.</p></div> : campaigns.data?.map((campaign) => <button type="button" key={campaign.id} onClick={() => setSelected(campaign)} className={`w-full rounded-md border p-4 text-left transition-colors ${selected?.id === campaign.id ? "border-primary bg-primary/5" : "hover:bg-muted/40"}`}><div className="flex justify-between gap-3"><div><p className="font-semibold">{campaign.name}</p><p className="mt-1 line-clamp-1 text-xs text-muted-foreground">{campaign.objectivePrompt || "No objective set"}</p></div><span className="h-fit rounded bg-muted px-2 py-1 text-xs font-semibold">{campaign.status}</span></div><div className="mt-4 grid grid-cols-5 gap-2 text-center text-xs"><Metric value={campaign.metrics.total} label="total" /><Metric value={campaign.metrics.queued} label="queued" /><Metric value={campaign.metrics.dialing} label="live" /><Metric value={campaign.metrics.blocked} label="blocked" /><Metric value={campaign.metrics.goalMet} label="goals" /></div></button>)}</div>
      <aside className="rounded-md border bg-card p-4">{selected ? <div className="space-y-5"><div className="flex justify-between gap-2"><div><h2 className="font-semibold">{selected.name}</h2><p className="text-xs text-muted-foreground">Queue refreshes every five seconds</p></div><div className="flex flex-wrap justify-end gap-1">{selected.status === "RUNNING" ? <Button size="sm" variant="outline" onClick={() => lifecycle.mutate({ id: selected.id, status: "PAUSED" })}><Pause className="mr-1 h-3.5 w-3.5" /> Pause</Button> : selected.status !== "STOPPED" && selected.status !== "COMPLETED" ? <Button size="sm" onClick={() => lifecycle.mutate({ id: selected.id, status: "RUNNING" })}><Play className="mr-1 h-3.5 w-3.5" /> Launch</Button> : null}<Button size="sm" variant="outline" onClick={() => clone.mutate(selected.id)}><Copy className="mr-1 h-3.5 w-3.5" /> A/B clone</Button>{selected.status !== "STOPPED" && selected.status !== "COMPLETED" && <Button size="sm" variant="destructive" onClick={() => stop.mutate(selected.id)}><Square className="mr-1 h-3.5 w-3.5" /> Stop</Button>}</div></div>
        <div className="rounded border border-amber-500/30 bg-amber-500/5 p-3 text-xs text-muted-foreground">Each queue item is rechecked against DNC, consent, calling windows, and holiday rules immediately before a call is created.</div>
        <div><Label>Import CSV contacts</Label><div className="mt-2 flex gap-2"><Input value={phoneColumn} onChange={(e) => setPhoneColumn(e.target.value)} className="max-w-32" placeholder="phone column" /><label><Button asChild variant="outline" size="sm"><span><FileUp className="mr-1 h-3.5 w-3.5" /> Select</span></Button><input className="sr-only" type="file" accept=".csv,text/csv" onChange={onFile} /></label></div>{csv && <><p className="mt-2 text-xs text-muted-foreground">Review mapping before import. Phone: <code>{phoneColumn}</code>; variables: {variableColumns.join(", ") || "none"}.</p><div className="mt-2 flex gap-2"><Button size="sm" variant="outline" disabled={previewCsv.isPending} onClick={() => previewCsv.mutate()}>Preview & review</Button><Button size="sm" disabled={!importReport || importCsv.isPending} onClick={() => importCsv.mutate()}>{importCsv.isPending ? <Loader2 className="mr-2 h-3.5 w-3.5 animate-spin" /> : <Upload className="mr-2 h-3.5 w-3.5" />} Confirm import</Button></div>{importReport && <div className="mt-2 rounded border p-2 text-xs"><p className="font-medium">{importReport.total} rows reviewed · {importReport.allowed} allowed · {importReport.blocked} blocked</p>{importReport.rows.slice(0, 5).map((row) => <p key={row.row} className="text-muted-foreground">Row {row.row}: {row.phone ?? "invalid"} — {row.reason ?? row.state}</p>)}</div>}</>}</div>
        <div><div className="mb-2 flex items-center gap-2"><Users className="h-4 w-4" /><h3 className="text-sm font-semibold">Recent contacts</h3></div><div className="max-h-64 overflow-y-auto rounded border">{contacts.isLoading ? <p className="p-4 text-sm text-muted-foreground">Loading contacts…</p> : contacts.data?.length ? contacts.data.map((contact) => <div key={contact.id} className="border-b p-2.5 text-xs last:border-0"><div className="flex justify-between"><span className="font-mono">{contact.phoneE164}</span><span className={contact.state === "BLOCKED" ? "text-destructive" : contact.state === "DONE" ? "text-emerald-600" : "text-muted-foreground"}>{contact.state}</span></div><p className="mt-1 text-muted-foreground">{contact.blockReason || contact.lastDisposition || `Attempt ${contact.attempts}`}</p></div>) : <p className="p-4 text-sm text-muted-foreground">No contacts imported.</p>}</div></div>
        <div><div className="mb-2 flex items-center justify-between"><div className="flex items-center gap-2"><Activity className="h-4 w-4" /><h3 className="text-sm font-semibold">Disposition monitor</h3></div><a className="inline-flex items-center text-xs text-primary" href={`${BASE}/api/v1/campaigns/${selected.id}/dispositions?format=csv`}><Download className="mr-1 h-3.5 w-3.5" /> CSV</a></div><div className="max-h-32 overflow-y-auto rounded border">{dispositions.data?.length ? dispositions.data.slice().reverse().slice(0, 10).map((item) => <p key={item.id} className="border-b p-2 text-xs last:border-0"><b>{item.code}</b> <span className="text-muted-foreground">{item.summaryText || new Date(item.createdAt).toLocaleString()}</span></p>) : <p className="p-3 text-xs text-muted-foreground">No dispositions yet.</p>}</div></div>
        <div><div className="mb-2 flex items-center gap-2"><CalendarClock className="h-4 w-4" /><h3 className="text-sm font-semibold">Scheduled callbacks</h3></div><div className="rounded border">{callbacks.data?.length ? callbacks.data.slice(0, 5).map((item) => <p key={item.id} className="border-b p-2 text-xs last:border-0">{new Date(item.scheduledFor).toLocaleString()} — {item.note || "No note"} {item.fulfilled ? "· fulfilled" : ""}</p>) : <p className="p-3 text-xs text-muted-foreground">No callbacks booked.</p>}</div></div>
      </div> : <div className="flex min-h-72 flex-col items-center justify-center text-center text-muted-foreground"><Activity className="h-7 w-7" /><p className="mt-3 text-sm">Select a campaign to manage its queue.</p></div>}</aside>
    </div>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Create campaign</DialogTitle><DialogDescription>Set the voice bot, goal, schedule, and safe concurrency limit before importing contacts.</DialogDescription></DialogHeader><div className="space-y-3"><div><Label>Name</Label><Input className="mt-1" value={name} onChange={(e) => setName(e.target.value)} placeholder="Q4 renewal outreach" /></div><div><Label>Voice bot</Label><select className="mt-1 h-9 w-full rounded-md border bg-background px-3 text-sm" value={botId} onChange={(e) => setBotId(e.target.value)}><option value="">Select a bot</option>{bots.data?.map((bot) => <option key={bot.id} value={bot.id}>{bot.displayName}</option>)}</select></div><div><Label>Objective & talk-track context</Label><Textarea className="mt-1" value={objectivePrompt} onChange={(e) => setObjective(e.target.value)} placeholder="Confirm renewal interest and book a callback." /></div><div className="grid grid-cols-2 gap-2"><div><Label>Start (optional)</Label><Input className="mt-1" type="datetime-local" value={startAt} onChange={(e) => setStartAt(e.target.value)} /></div><div><Label>End (optional)</Label><Input className="mt-1" type="datetime-local" value={endAt} onChange={(e) => setEndAt(e.target.value)} /></div><div><Label>Calling window start</Label><Input className="mt-1" type="time" value={windowStart} onChange={(e) => setWindowStart(e.target.value)} /></div><div><Label>Calling window end</Label><Input className="mt-1" type="time" value={windowEnd} onChange={(e) => setWindowEnd(e.target.value)} /></div></div><div><Label>Concurrent calls</Label><Input className="mt-1" type="number" min="1" max="50" value={concurrencyCap} onChange={(e) => setConcurrency(e.target.value)} /></div></div><DialogFooter><Button disabled={!name || !botId || create.isPending} onClick={() => create.mutate()}>{create.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />} Create campaign</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
function Metric({ value, label }: { value: number; label: string }) { return <div><p className="font-semibold">{value}</p><p className="text-muted-foreground">{label}</p></div>; }